version: '3'
services:
  webspoon:
    image: hiromuhota/webspoon
    ports:
      - "8080:8080"
    volumes:
       - ./files:/home/files # bind your files here on ./files to see on /Home/files
       - ./lib/mariadb-java-client-2.7.4.jar:/usr/local/tomcat/lib/mariadb-java-client-2.7.4.jar # bind your drivers here on ./lib to see on /usr/local/tomcat/lib
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    networks: 
        - mariadbForSpoon
networks:
  mariadbForSpoon:
    name: mariadbForSpoon
    driver: "bridge"
    external: true